<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle = \Yii::app()->name . ' - Contact Us';
//$this->breadcrumbs=array('Contact',);
?>

<style>
/**
 * CSS styles for forms generated by yiic.
 *
 * The styles can be applied to the following form structure:
 *
 * <div class="form">
 *     <div class="row">
 *         <label for="inputid">xyz</label>
 *         <input name="inputid" id="inputid" type="text" />
 *         <p class="hint">hint text</p>
 *     </div>
 *     <div class="row">
 *         <label for="inputid">xyz</label>
 *         <input name="inputid" id="inputid" type="text" />
 *         <p class="hint">hint text</p>
 *     </div>
 *     <div class="row buttons">
 *         <label for="inputid">xyz</label>
 *         <input name="inputid" id="inputid" type="text" />
 *         <p class="hint">hint text</p>
 *     </div>
 * </div>
 *
 * The above code will render the labels and input fields in separate lines.
 * In order to render them in the same line, please use the "wide" form as follows,
 *
 * <div class="wide form">
 *     ......
 * </div>
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @link http://www.yiiframework.com/
 * @copyright 2008-2010 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

.form fieldset, fieldset .form
{
	border: 1px solid #DDD;
	padding: 10px;
	margin: 0 0 10px 0;
        border-radius:7px;
    -moz-border-radius:7px;
}

div.form label
{
	font-weight: bold;
	font-size: 0.9em;
	display: block;
}

div.form .row
{
	margin: 5px 0;
}

div.form .hint
{
	margin: 0;
	padding: 0;
	color: #999;
}

div.form .note
{
	font-style: italic;
}

div.form span.required
{
	color: red;
}

div.form div.error label:first-child,
div.form label.error,
div.form span.error
{
	color: #C00;
}

div.form div.error input,
div.form div.error textarea,
div.form div.error select,
div.form input.error,
div.form textarea.error,
div.form select.error
{
	background: #FEE;
	border-color: #C00;
}

div.form div.success input,
div.form div.success textarea,
div.form div.success select,
div.form input.success,
div.form textarea.success,
div.form select.success
{
	background: #E6EFC2;
	border-color: #C6D880;
}

div.form div.success label
{
	color: inherit;
}

div.form .errorSummary
{
	border: 2px solid #C00;
	padding: 7px 7px 12px 7px;
	margin: 0 0 20px 0;
	background: #FEE;
	font-size: 0.9em;
}

div.form .errorMessage
{
	color: red;
	font-size: 0.9em;
}

div.form .errorSummary p
{
	margin: 0;
	padding: 5px;
}

div.form .errorSummary ul
{
	margin: 0;
	padding: 0 0 0 20px;
}

div.wide.form label
{
	float: left;
	margin-right: 10px;
	position: relative;
	text-align: right;
	width: 100px;
}

div.wide.form .row
{
	clear: left;
}

div.wide.form .buttons, div.wide.form .hint, div.wide.form .errorMessage
{
	clear: left;
	padding-left: 110px;
}
.form-horizontal input
{
      display: inline-block;
  margin-bottom: 0;
  vertical-align: middle;
} 
input[type="text"]{
      border: 1px solid #ccc;
      transition: border linear .2s,box-shadow linear .2s;
        height: 20px;
  padding: 4px 6px;
 
  font-size: 14px;
  line-height: 20px;
}
</style>

<?php if (\Yii::app()->user->hasFlash('contact')): ?>

    <div class="ui flash-success">
        <?php echo \Yii::app()->user->getFlash('contact'); ?>
    </div>

<?php else: ?>
    <div class="ui  grid">
        <div class="row">
            <div class="one wide column"></div>
            <div class="three wide column">
                <h2 >Contacts</h2>
                <div class="ui items">
                    <div class="item">
                       
                         <a onclick="showMap('Noida');" href="#mapsPlace">B2B Division</a><br>
                    <br>
                    <div class="content">
                        <strong>Belair Travel &amp; Cargo (P) Ltd.</strong><br>
                        <i class="call icon"></i>&nbsp;&nbsp; <a href="tel:+91-120-4887700">+91-120-4887700</a><br>
                        <i class="call icon"></i>&nbsp;&nbsp; +91-011-23328288<br>
                        <i class="mail icon"></i>&nbsp;&nbsp; <a target="_blank" href="mailto:sales@belair.in">sales@belair.in</a><br>
                        2nd Floor, C-101, Sector - 2, <br>
                        Noida - 201301, U.P.<br>
                    </div>
                         </div>
                    <br><br>
                   <div class="item">
                    <a onclick="showMap('Head');" href="#mapsPlace">Corporate Division/Head Office</a><br>
                    <br>
                    <div class="content">
                    <strong>Belair Travel &amp; Cargo (P) Ltd.</strong><br>
                    <i class="call icon"></i>&nbsp;&nbsp; <a href="tel:+91-011-42521000">+91-011-42521000</a><br>
                    <i class="call icon"></i>&nbsp;&nbsp; +91-011-23328288<br>
                    <i class="mail icon"></i>&nbsp;&nbsp; <a target="_blank" href="mailto:corporates@belair.in">corporates@belair.in</a><br>
                    10-B Scindia House,<br>
                    Connaught Place,<br>
                    New Delhi - 110001<br>
                    </div>
                    </div>
                    <br><br>
                    <div class="item">
                    <a onclick="showMap('Bangalore');" href="#mapsPlace">Bangalore</a><br>
                   <br>
                    <div class="content">
                    <strong>Belair Travel &amp; Cargo (P) Ltd.  (Bangalore)</strong><br>
                    <i class="call icon"></i>&nbsp;&nbsp; <a href="tel:+91-80-41124600">+91-80-41124600</a><br>
                    <i class="call icon"></i>&nbsp;&nbsp; +91-80-25594233<br>
                    <i class="mail icon"></i>&nbsp;&nbsp; <a target="_blank" href="mailto:blr@belairindia.com">blr@belairindia.com</a><br>
                    SUITE 711-A, MITTAL TOWER<br>
                    6, MAHATMA GANDHI ROAD,<br>
                    BANGALORE - 560001<br><br>
                    </div>
                     </div>
                </div>
            </div>
            <div class="ten wide column" id="mapsPlace">
                <br><br>
                <iframe width="100%" height="580" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f81670e2ac29be0c2&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=28.630986,77.220722&amp;spn=0.00452,0.006866&amp;z=17&amp;iwloc=0004f8168592a41f0c778&amp;output=embed"></iframe><br /><small>View <a href="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f81670e2ac29be0c2&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=28.630986,77.220722&amp;spn=0.00452,0.006866&amp;z=17&amp;iwloc=0004f8168592a41f0c778&amp;source=embed" style="color:#0000FF;text-align:left">Belair Travel &amp; Cargo P. Ltd</a> in a larger map</small>

            </div>
        </div>
    </div>
 <div class="ui  grid">
        <div class="row">
            <div class="one wide column"></div>
            <div class="eight wide column">

    <div class="form span8">

        <?php
        $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
            'id' => 'contact-form',
            'layout' => TbHtml::FORM_LAYOUT_HORIZONTAL,
            'enableClientValidation' => true,
            'clientOptions' => array(
                'validateOnSubmit' => true,
            ),
        ));
        ?>
        <h3>Contact form:</h3>
        <p class="note">Fields with <span class="required">*</span> are required.</p>
        <fieldset>

            <?php
            echo $form->errorSummary($model);
            echo $form->textFieldControlGroup($model, 'name');
            echo $form->textFieldControlGroup($model, 'email');
            echo $form->textFieldControlGroup($model, 'subject', array('size' => 60, 'maxlength' => 128));
            echo $form->textAreaControlGroup($model, 'body', array('rows' => 6, 'style' => 'width: 90%;'));

            if (CCaptcha::checkRequirements()) {
                echo $form->textFieldControlGroup($model, 'verifyCode');
                $this->widget('CCaptcha');
            }
            ?>
            <div class="hint">Please enter the letters as they are shown in the image above.
                <br/>Letters are not case-sensitive.</div>
            <?php
            echo TbHtml::formActions(array(
                TbHtml::submitButton('Submit', array('color' => TbHtml::BUTTON_COLOR_PRIMARY)),
                TbHtml::resetButton('Reset'),
            ));
            $this->endWidget();
            ?>
        </fieldset>

    </div><!-- form -->
            </div></div></div>
<?php endif; ?>

<script>
    function showMap(map) {
        var maps = new Array;
        maps['Noida'] = '<iframe width="100%" height="580" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f816a5508432be4ab&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=28.586915,77.315941&amp;spn=0.009044,0.013733&amp;z=16&amp;iwloc=0004f816a8e7efe51141c&amp;output=embed"></iframe><br /><small>View <a target="_blank" href="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f816a5508432be4ab&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=28.586915,77.315941&amp;spn=0.009044,0.013733&amp;z=16&amp;iwloc=0004f816a8e7efe51141c&amp;source=embed" style="color:#0000FF;text-align:left">Belair Travel &amp; Cargo P. Ltd (B2B Division)</a> in a larger map</small>';
        maps['Head'] = '<iframe width="100%" height="580" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f81670e2ac29be0c2&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=28.630986,77.220722&amp;spn=0.00452,0.006866&amp;z=17&amp;iwloc=0004f8168592a41f0c778&amp;output=embed"></iframe><br /><small>View <a href="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f81670e2ac29be0c2&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=28.630986,77.220722&amp;spn=0.00452,0.006866&amp;z=17&amp;iwloc=0004f8168592a41f0c778&amp;source=embed" style="color:#0000FF;text-align:left">Belair Travel &amp; Cargo P. Ltd</a> in a larger map</small>';
        maps['Bangalore'] = '<iframe width="100%" height="580" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f81694b48eec4edc1&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=12.975139,77.614481&amp;spn=0.010037,0.013733&amp;z=16&amp;iwloc=0004f8169be5b87605d8a&amp;output=embed"></iframe><br /><small>View <a href="https://www.google.co.in/maps/ms?msid=204193885765947401061.0004f81694b48eec4edc1&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=12.975139,77.614481&amp;spn=0.010037,0.013733&amp;z=16&amp;iwloc=0004f8169be5b87605d8a&amp;source=embed" style="color:#0000FF;text-align:left">Belair Travel &amp; Cargo P. Ltd (Bangalore)</a> in a larger map</small>';
        $('#mapsPlace').html(maps[map]);
        return false;
    }
</script>